source: src
paths:
  data: _data
  collections: ''
  layouts: _includes
  static: ''
  uploads: uploads
  includes: _includes
  pages: ''
collections_config:
  data:
    path: _data
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: ''
    output: true
    filter: strict
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Etc/UTC
_inputs:
  layout : 
    hidden : true

  primary-color : "rgb(71, 85, 94)"
  secondary-color : "rgb(129, 163, 184)"
  tertiary-color : "rgb(5, 74, 116)"
  dark-color : "rgb(41, 33, 36)"
  white-color : "#EEEEEE"
  font-family-title: "Nova Mono"
  font-family-default: "Roboto"
